# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('replay', models.CharField(blank=True, max_length=500, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Uploads')),
            ],
        ),
    ]
