# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_commend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commend',
            old_name='replay',
            new_name='reply',
        ),
    ]
