# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20180712_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(to='user_app.Email'),
        ),
    ]
