# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20180712_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_email', to='user_app.Email'),
        ),
    ]
